### ISSUE TITLE
Enable json logging

### ISSUE THREAD

**Issue by eBusEntwHOFM** [stripe/stripe-mirakl-connector#53]
Hi folks,

we are trying to enable logging in JSON format, in order to ship logs to the Elasticsearch.

Following configuration doesn't work :(

```
config/packages/prod/monolog.yaml

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
            formatter: monolog.formatter.json
```

Do you have a hint?

Best regards
